version: "3.9"

services:
  tars-bot:
    container_name: tars-bot
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./main.py:/app/main.py:ro
      - ./data:/app/data
    command: python /app/main.py

